### ISSUE TITLE
Multiple include files are missing

### ISSUE THREAD

**Issue by vsydoruk-cirrus** [cad-audioNDSP/HiFi_4_NDSP#1]
I am trying to compile the library with the provided make file using xt-clnag compiler and I have multiple missing include file errors:

'stereo_bkfir16x16_common.h' file not found
'stereo_bkfir32x32_common.h' file not found
'stereo_bqriir16x16_df1_common.h' file not found
'stereo_bqriir32x16_df1_common.h' file not found
'stereo_bqriir32x32_df1_common.h' file not found
'stereo_bqriirf_df1_common.h' file not found
 'raw_corr32x32ep.h' file not found
 'vec_recip_table.h' file not found
fatal error: 'recip_table.h' file not found
'sine_table32.h' file not found
'polyrsqrtq23_tbl.h' file not found
'pif_tbl.h' file not found
'sqrt2f_tbl.h' file not found
...
The list is not extensive. It feels like a big chunk of the include files are completely missing.

**Comment by cad-audioNDSP** [comment]
Hi, Please download the source files from the .zip folder - [NDSP_HiFi5_v420.zip] (https://github.com/cad-audioNDSP/HiFi_4_NDSP/blob/main/NDSP_HiFi4/NDSP_HiFi5_v420.zip).

**Comment by cad-audioNDSP** [comment]
Please take the source code from the zip 
https://github.com/cad-audioNDSP/HiFi_4_NDSP/blob/main/NDSP_HiFi4/NDSP_HiFi4_v420.zip

**Comment by vsydoruk-cirrus** [comment]
Thank you for the quick response, I am going to give it a try and report back.
I am also very keen in evaluating the CMSIS DSP lib that is advertised on Cadence web site https://www.cadence.com/en_US/home/tools/ip/tensilica-ip/hifi-dsps/software.html#libraries . Unfortunately I can't find any sources, would you be able to point me to them as well? 

Thank you,
Volodymyr

**Comment by cad-audioNDSP** [comment]
For any query related to CMSIS library on HiFi DSP, please contact through Sales channel/customer support portal.
